-- KeyStats cloud sync schema (private deployment).
-- Privacy note: key_press_counts / app_stats are aggregate breakdowns only,
-- not raw keystroke content. Omit or encrypt these columns for stricter privacy.
-- UUIDs are generated by the application (no pgcrypto extension required).

CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS devices (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    platform TEXT NOT NULL CHECK (platform IN ('macos', 'windows', 'linux')),
    device_name TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_sync_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_devices_user_id ON devices(user_id);

CREATE TABLE IF NOT EXISTS daily_stats (
    id BIGSERIAL PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    device_id UUID NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
    date DATE NOT NULL,
    key_presses INT NOT NULL DEFAULT 0,
    left_clicks INT NOT NULL DEFAULT 0,
    right_clicks INT NOT NULL DEFAULT 0,
    side_back_clicks INT NOT NULL DEFAULT 0,
    side_forward_clicks INT NOT NULL DEFAULT 0,
    mouse_distance DOUBLE PRECISION NOT NULL DEFAULT 0,
    scroll_distance DOUBLE PRECISION NOT NULL DEFAULT 0,
    peak_kps INT NOT NULL DEFAULT 0,
    peak_cps INT NOT NULL DEFAULT 0,
    -- PRIVACY: optional aggregate JSON; keys are key names like "Cmd+C", not typed content.
    key_press_counts JSONB,
    -- PRIVACY: per-app aggregate counts keyed by bundle id / process name.
    app_stats JSONB,
    version BIGINT NOT NULL DEFAULT 1,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (user_id, device_id, date)
);

CREATE INDEX IF NOT EXISTS idx_daily_stats_user_date ON daily_stats(user_id, date);
CREATE INDEX IF NOT EXISTS idx_daily_stats_device_date ON daily_stats(device_id, date);
